# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainDialog(object):
    def setupUi(self, mainDialog):
        mainDialog.setObjectName("mainDialog")
        mainDialog.resize(480, 250)
        self.lineEditFileNameTag = QtWidgets.QLineEdit(mainDialog)
        self.lineEditFileNameTag.setGeometry(QtCore.QRect(195, 60, 161, 22))
        self.lineEditFileNameTag.setObjectName("lineEditFileNameTag")
        self.spinBoxPeriod = QtWidgets.QSpinBox(mainDialog)
        self.spinBoxPeriod.setGeometry(QtCore.QRect(195, 25, 61, 22))
        self.spinBoxPeriod.setMaximum(43200)
        self.spinBoxPeriod.setObjectName("spinBoxPeriod")
        self.buttonStartCapture = QtWidgets.QPushButton(mainDialog)
        self.buttonStartCapture.setGeometry(QtCore.QRect(5, 25, 161, 28))
        self.buttonStartCapture.setObjectName("buttonStartCapture")
        self.textEditStatus = QtWidgets.QTextEdit(mainDialog)
        self.textEditStatus.setGeometry(QtCore.QRect(10, 90, 461, 141))
        self.textEditStatus.setObjectName("textEditStatus")
        self.label = QtWidgets.QLabel(mainDialog)
        self.label.setGeometry(QtCore.QRect(190, 5, 96, 16))
        self.label.setObjectName("label")
        self.buttonStopCapture = QtWidgets.QPushButton(mainDialog)
        self.buttonStopCapture.setGeometry(QtCore.QRect(5, 60, 161, 28))
        self.buttonStopCapture.setObjectName("buttonStopCapture")

        self.retranslateUi(mainDialog)
        QtCore.QMetaObject.connectSlotsByName(mainDialog)

    def retranslateUi(self, mainDialog):
        _translate = QtCore.QCoreApplication.translate
        mainDialog.setWindowTitle(_translate("mainDialog", "Dialog"))
        self.buttonStartCapture.setText(_translate("mainDialog", "Start Screen Capture"))
        self.label.setText(_translate("mainDialog", "Period (seconds)"))
        self.buttonStopCapture.setText(_translate("mainDialog", "Stop Screen Capture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainDialog = QtWidgets.QDialog()
    ui = Ui_mainDialog()
    ui.setupUi(mainDialog)
    mainDialog.show()
    sys.exit(app.exec_())
